on: [push]

jobs:
  gist-sync:
    name: gist-sync
    runs-on: ubuntu-latest
    steps:
    #PIC18F4550
      - name: Checkout
        uses: actions/checkout@v2
      - uses: vhperaltaj/gist-sync-action@v1.0.0
        id: PIC18F4550
        with:
          auth: ${{ secrets.GIST_TOKEN }}
          gist_url: https://gist.github.com/microside-mx/5b68423d6de5b53fb19a5e870da4654e
          gist_title: 18-MPLAB-DS18B20-4550.c
          gist_description: Prácticas MPLABX
          github_file: Proyecto/PIC18F4550/DS18B20_4550.X/main.c
          file_encoding: ISO-8859-1
    #PIC18F45K50
      - name: Checkout
        uses: actions/checkout@v2
      - uses: vhperaltaj/gist-sync-action@v1.0.0
        id: PIC18F45K50
        with:
          auth: ${{ secrets.GIST_TOKEN }}
          gist_url: https://gist.github.com/microside-mx/081443231c7a699644e23f8b6890118f
          gist_title: 18-MPLAB-DS18B20.c
          gist_description: Prácticas MPLABX
          github_file: Proyecto/PIC18F45K50/DS18B20_45K50.X/main.c
          file_encoding: ISO-8859-1